apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-backend
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/toannd135/btl-shoeshop-backend.git'
      targetRevision: HEAD
      path: 'backend-chart'
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shoeshop-web
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
